# Unit 4

### 4.1 Data Analysis with Pandas

In [30]:
import pandas as pd

In [31]:
portfolio_df = pd.DataFrame({'Stock': ['Oracle', 'Lloyds', 'Shell', 'Tesla', 'Rolls-Royce'],
                            'Ticker': ['ORCL', 'LLOY.L', 'SHEL.L', 'TSLA', 'RRL.XC'],
                            'Price': [150.28, 111.15 ,3551.00, 365.44, 1454.00],
                            'Shares': [20, 534, 624, 35, 45]})

portfolio_df.describe()

             Price      Shares
count     5.000000    5.000000
mean   1126.374000  251.600000
std    1461.900292  300.694696
min     111.150000   20.000000
25%     150.280000   35.000000
50%     365.440000   45.000000
75%    1454.000000  534.000000
max    3551.000000  624.000000

In [32]:
sum((portfolio_df['Price'] * portfolio_df['Shares']))

2356404.1

### 4.2 Handling Missing Data

In [33]:
investors_df = pd.read_csv('investors_data.csv')
investors_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
1,Sherif,George,54,950000.0,30.0,conservative,retire
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
6,Chris,Peter,38,NaN,8.0,moderate,kids education
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

In [34]:
investors_df['Years with Investment Firm'].median()
investors_df.fillna(investors_df['Years with Investment Firm'].median(), inplace=True)

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
1,Sherif,George,54,950000.0,30.0,conservative,retire
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
3,Victoria,Keller,43,300901.0,9.0,moderate,investment property
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
6,Chris,Peter,38,9.0,8.0,moderate,kids education
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

### 4.3 DataFrame Filtering and Sorting

In [35]:
investors_df = pd.read_csv('investors_data.csv')
investors_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
1,Sherif,George,54,950000.0,30.0,conservative,retire
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
6,Chris,Peter,38,NaN,8.0,moderate,kids education
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

In [36]:
investors_df.sort_values(by='Age', ascending=False, inplace=True)
investors_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
1,Sherif,George,54,950000.0,30.0,conservative,retire
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
6,Chris,Peter,38,NaN,8.0,moderate,kids education
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

In [37]:
high_net_worth = investors_df[investors_df['Portfolio Size'] >= 500000]
high_net_worth

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
1,Sherif,George,54,950000.0,30.0,conservative,retire

In [38]:
high_net_worth['Portfolio Size'].sum()

np.float64(1850000.0)

### 4.4 DataFrames and Functions

In [39]:
investors_df = pd.read_csv('investors_data.csv')
investors_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
1,Sherif,George,54,950000.0,30.0,conservative,retire
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
6,Chris,Peter,38,NaN,8.0,moderate,kids education
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

In [40]:
def rankings(portfolio_size):
    if portfolio_size < 100000:
        return 'Low'
    elif portfolio_size >= 100000 and portfolio_size <= 500000:
        return 'Medium'
    else:
        return 'High'

In [41]:
investors_df['Rank'] = investors_df['Portfolio Size'].apply(rankings)
investors_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Rank
0,Ryan,David,32,80100.0,5.0,aggressive,buy house,Low
1,Sherif,George,54,950000.0,30.0,conservative,retire,High
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education,Medium
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property,Medium
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans,Low
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire,Medium
6,Chris,Peter,38,NaN,8.0,moderate,kids education,High
7,Nancy,Smith,55,900000.0,17.0,conservative,retire,High
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early,Low

### 4.5 DataFrames Concatenation and Merging

In [42]:
investors_df = pd.read_csv('investors_data.csv')
investors_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
1,Sherif,George,54,950000.0,30.0,conservative,retire
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
6,Chris,Peter,38,NaN,8.0,moderate,kids education
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

In [43]:
new_client_df = pd.DataFrame({'Client ID': ['C1'],
                            'First Name': ['Bob'],
                            'Last Name': ['Rob'],
                            'Age': [67],
                            'Portfolio Size': [670000],
                            'Years with Investment Firm': [6],
                            'Risk Tolerance': ['aggressive'],
                            'Goal': ['Larp'],
                            'Salaries': [67000],
                            'Job Title': ['Senior Larper']})

investors_df = pd.concat([investors_df, new_client_df], axis=0)
investors_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Client ID,Salaries,Job Title
0,Ryan,David,32,80100.0,5.0,aggressive,buy house,NaN,NaN,NaN
1,Sherif,George,54,950000.0,30.0,conservative,retire,NaN,NaN,NaN
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education,NaN,NaN,NaN
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property,NaN,NaN,NaN
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans,NaN,NaN,NaN
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire,NaN,NaN,NaN
6,Chris,Peter,38,NaN,8.0,moderate,kids education,NaN,NaN,NaN
7,Nancy,Smith,55,900000.0,17.0,conservative,retire,NaN,NaN,NaN
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early,NaN,NaN,NaN
0,Bob,Rob,67,670000.0,6.0,aggressive,Larp,C1,67000.0,Senior Larper

In [44]:
investors_df.reset_index(drop = True)

AttributeError: 'DataFrame' object has no attribute 'top'

### 4.6 Financial Markets Data

In [ ]:
import yfinance as yf
import datetime

meta = yf.Ticker('META')
apple = yf.Ticker('AAPL')
spotify = yf.Ticker('SPOT')
pg = yf.Ticker('PG')

In [ ]:
bitcoin = yf.Ticker('BTC-USD')

print(bitcoin.info['circulatingSupply'])
print(bitcoin.info['previousClose'])

20083744
77270.22

In [ ]:
startDate = datetime.datetime(2022,2,22)
endDate = datetime.datetime(2022,2,28)
vol = apple.history(start=startDate, end=endDate)['Volume']
vol['2022-02-22 00:00:00-05:00']

np.int64(91162800)